.TH LIBAR2 7 LIBAR2
.SH NAME
libar2 - Library for the Argon2-family of hashing functions

.SH DESCRIPTION
.B libar2
is a C library that implements the family of Argon2
key derivation function, including Argon2d, Argon2i,
and Argon2id, as well as Argon2ds which was not part
of the submission to the Password Hashing Competition
of 2013, which Argon2 won in 2015. As a key derivation
function, Argon2 is well-suited for cryptographically
hashing (one-way encrypting) passwords.

.SH SEE ALSO
.BR libar2simplified (7),
.BR libar2_decode_base64 (3),
.BR libar2_decode_params (3),
.BR libar2_encode_base64 (3),
.BR libar2_encode_params (3),
.BR libar2_erase (3),
.BR libar2_hash (3),
.BR libar2_hash_buf_size (3),
.BR libar2_latest_argon2_version (3),
.BR libar2_string_to_type (3),
.BR libar2_string_to_version (3),
.BR libar2_type_to_string (3),
.BR libar2_validate_params (3),
.BR libar2_version_to_string (3),
.BR libar2_version_to_string_proper (3)
